version: '3.8'
services:
  validator1:
    restart: "on-failure"
    image: hyperledger/besu:latest
    env_file:
      - ./config/besu/.env
    entrypoint:
      - /bin/bash
      - -c
      - |
        /opt/besu/bin/besu \
        --config-file=/config/config.toml \
        --p2p-host=validator1 \
        --rpc-http-api=EEA,WEB3,ETH,NET,TRACE,DEBUG,ADMIN,TXPOOL,PRIV,PERM,QBFT \
        --rpc-ws-api=EEA,WEB3,ETH,NET,TRACE,DEBUG,ADMIN,TXPOOL,PRIV,PERM,QBFT ;
    ports:
      - 21001:8545/tcp
      - 30303
      - 9545
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=validator1,service.version=latest
    labels:
      - "consensus=besu"
    volumes:
      - ./config/besu/:/config
      - ./config/nodes/validator1:/opt/besu/keys
      - ./logs/besu:/tmp/besu
    networks:
      quorum-dev-quickstart:
        ipv4_address: 172.168.16.11

#   validator2:
#     restart: "on-failure"
#     image: hyperledger/besu:latest
#     env_file:
#       - ./config/besu/.env
#     entrypoint:
#       - /bin/bash
#       - -c
#       - |
#         /opt/besu/bin/besu \
#         --config-file=/config/config.toml \
#         --p2p-host=validator2 \
#         --rpc-http-api=EEA,WEB3,ETH,NET,TRACE,DEBUG,ADMIN,TXPOOL,PRIV,PERM,QBFT \
#         --rpc-ws-api=EEA,WEB3,ETH,NET,TRACE,DEBUG,ADMIN,TXPOOL,PRIV,PERM,QBFT ;
#     ports:
#       - 21002:8545/tcp
#       - 30303
#       - 9545
#     environment:
#       - OTEL_RESOURCE_ATTRIBUTES=service.name=validator2,service.version=latest
#     labels:
#       - "consensus=besu"
#     volumes:
#       - ./config/besu/:/config
#       - ./config/nodes/validator2:/opt/besu/keys
#       - ./logs/besu:/tmp/besu
#     depends_on:
#       - validator1
#     networks:
#       quorum-dev-quickstart:
#         ipv4_address: 172.168.16.12

#   validator3:
#     restart: "on-failure"
#     image: hyperledger/besu:latest
#     env_file:
#       - ./config/besu/.env
#     entrypoint:
#       - /bin/bash
#       - -c
#       - |
#         /opt/besu/bin/besu \
#         --config-file=/config/config.toml \
#         --p2p-host=validator3 \
#         --rpc-http-api=EEA,WEB3,ETH,NET,TRACE,DEBUG,ADMIN,TXPOOL,PRIV,PERM,QBFT \
#         --rpc-ws-api=EEA,WEB3,ETH,NET,TRACE,DEBUG,ADMIN,TXPOOL,PRIV,PERM,QBFT ;
#     ports:
#       - 21003:8545/tcp
#       - 30303
#       - 9545
#     environment:
#       - OTEL_RESOURCE_ATTRIBUTES=service.name=validator3,service.version=latest
#     labels:
#       - "consensus=besu"
#     volumes:
#       - ./config/besu/:/config
#       - ./config/nodes/validator3:/opt/besu/keys
#       - ./logs/besu:/tmp/besu
#     depends_on:
#       - validator1
#     networks:
#       quorum-dev-quickstart:
#         ipv4_address: 172.168.16.13

#   validator4:
#     restart: "on-failure"
#     image: hyperledger/besu:latest
#     env_file:
#       - ./config/besu/.env
#     entrypoint:
#       - /bin/bash
#       - -c
#         /opt/besu/bin/besu \
#         --config-file=/config/config.toml \
#         --p2p-host=validator4 \
#         --rpc-http-api=EEA,WEB3,ETH,NET,TRACE,DEBUG,ADMIN,TXPOOL,PRIV,PERM,QBFT \
#         --rpc-ws-api=EEA,WEB3,ETH,NET,TRACE,DEBUG,ADMIN,TXPOOL,PRIV,PERM,QBFT ;
#     ports:
#       - 21004:8545/tcp
#       - 30303
#       - 9545
#     environment:
#       - OTEL_RESOURCE_ATTRIBUTES=service.name=validator4,service.version=latest
#     labels:
#       - "consensus=besu"
#     volumes:
#       - ./config/besu/:/config
#       - ./config/nodes/validator4:/opt/besu/keys
#       - ./logs/besu:/tmp/besu
#     depends_on:
#       - validator1
#     networks:
#       quorum-dev-quickstart:
#         ipv4_address: 172.168.16.14

  # rpcnode:
  #   restart: "on-failure"
  #   image: akaronte/besu:latest
  #   env_file:
  #     - ./config/besu/.env  
  #   #command: ls -la /config
  #   #command: besu --data-path=/booteth/data --genesis-file=/booteth/genesis.json --rpc-http-enabled --rpc-http-api=ADMIN,WEB3,ETH,NET,CLIQUE --rpc-http-host=0.0.0.0 --rpc-http-cors-origins='all' --graphql-http-enabled --host-allowlist='*'
  #   entrypoint:
  #     - besu \
  #       --config-file=/config/config.toml \
  #       --p2p-host=rpcnode \
  #       --rpc-http-api=EEA,WEB3,ETH,NET,TRACE,DEBUG,ADMIN,TXPOOL,PRIV,PERM,QBFT \
  #       --rpc-ws-api=EEA,WEB3,ETH,NET,TRACE,DEBUG,ADMIN,TXPOOL,PRIV,PERM,QBFT ;
  #   container_name: rpcnode
  #   environment:
  #     - OTEL_RESOURCE_ATTRIBUTES=service.name=rpcnode,service.version=latest
  #   volumes:
  #     - ./config/besu/:/config
  #     - ./config/nodes/rpcnode:/opt/besu/keys
  #     - ./logs/besu:/tmp/besu
  #   # depends_on:
  #   #   - validator1
  #   ports:
  #     - 8545:8545/tcp
  #     - 8546:8546/tcp
  #   networks:
  #     quorum-dev-quickstart:
  #       ipv4_address: 172.168.16.15


volumes:
  public-keys:
  prometheus:
  grafana:
  splunk:
  ethlogger:
  blockscoutpostgres:

networks:
  quorum-dev-quickstart:
    name: quorum-dev-quickstart
    driver: bridge
    ipam:
      config:
        - subnet: 172.168.16.0/24