version: "3.8"
services:
  booteth:
    image: besu
    container_name: booteth
    command: besu --data-path=/booteth/data --genesis-file=/booteth/genesis.json --rpc-http-enabled --rpc-http-api=ADMIN,WEB3,ETH,NET,CLIQUE --rpc-http-host=0.0.0.0 --rpc-http-cors-origins='all' --graphql-http-enabled --host-allowlist='*'
    volumes:
      - ./booteth:/booteth/
      - ./genesis.json:/booteth/genesis.json
    ports:
      - 30303:30303
      - 8545:8545
      - 8547:8547
    networks:
      besu_network:
        ipv4_address: 172.28.5.1
  nodeth1:
    image: besu
    container_name: nodeth1
    command: besu --data-path=/nodeth1/data --genesis-file=/nodeth1/genesis.json --rpc-http-enabled --graphql-http-enabled --bootnodes=enode://2d926fdb1b39410303c8fca548b5b3191f70f86b95a15faeb08db86338180b0e182935e8ad9a243110e2192dd7f1cc1360880e112485193b5689593bd8d37895@172.28.5.1:30303
    volumes:
      - ./nodeth1:/nodeth1/
      - ./genesis.json:/nodeth1/genesis.json
    networks:
      besu_network:
        ipv4_address: 172.28.5.2
  nodeth2:
    image: besu
    depends_on:
      - booteth
    container_name: nodeth2
    command: besu --data-path=data --genesis-file=/nodeth2/genesis.json --rpc-http-enabled --graphql-http-enabled --bootnodes=enode://2d926fdb1b39410303c8fca548b5b3191f70f86b95a15faeb08db86338180b0e182935e8ad9a243110e2192dd7f1cc1360880e112485193b5689593bd8d37895@172.28.5.1:30303
    volumes:
      - ./nodeth2:/nodeth2/
      - ./genesis.json:/nodeth2/genesis.json
    networks:
      besu_network:
        ipv4_address: 172.28.5.3
  nodeth3:
    image: besu
    depends_on:
      - booteth
    container_name: nodeth3
    command: besu --data-path=data --genesis-file=/nodeth3/genesis.json --rpc-http-enabled --graphql-http-enabled --bootnodes=enode://2d926fdb1b39410303c8fca548b5b3191f70f86b95a15faeb08db86338180b0e182935e8ad9a243110e2192dd7f1cc1360880e112485193b5689593bd8d37895@172.28.5.1:30303
    volumes:
      - ./nodeth3:/nodeth3/
      - ./genesis.json:/nodeth3/genesis.json
    networks:
      besu_network:
        ipv4_address: 172.28.5.4
networks:
  besu_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16



